import {ReactNode} from 'react';

// Generated by https://quicktype.io
export interface LoginData {
  email: string;
  password: string;
}

export interface LoginResponse {
  user: User;
  token: string;
}

export interface User {
  id: number;
  name: string;
  email: string;
  has2FA: boolean;
  img?: string;
}

//Tiendas
// Generated by https://quicktype.io
export interface TiendasResponse {
  tienda: Tiendas;
  id: string;
  tienda_nombre: string;
  tienda_clave: string;
  cadena_nombre: CadenaNombre;
  img_cadena: string;
  porcentaje: number;
}

export interface Tiendas {
  tienda_nombre: ReactNode;
  id: string;
  tiendas: TiendasResponse;
  tienda: string;
}

export enum CadenaNombre {
  Ba = 'BA',
  Supercenter = 'Supercenter',
  WalmartExpress = 'Walmart Express',
}

export enum ImgCadena {
  BaPNG = 'ba.png',
  WePNG = 'we.png',
  WmPNG = 'wm.png',
}
