import {ReactNode} from 'react';

// Generated by https://quicktype.io
export interface LoginData {
  email: string;
  password: string;
}

export interface LoginResponse {
  user: User;
  token: string;
}

export interface User {
  id: number;
  name: string;
  email: string;
  has2FA: boolean;
  img?: string;
}

//Tiendas
// Generated by https://quicktype.io
export interface TiendasResponse {
  cadena_nombre: any;
  id: string;
  tienda_nombre: string;
  tienda_clave: string;
  cadena: CadenaNombre;
  img_cadena: string;
  porcentaje: number;
}

export enum CadenaNombre {
  Ba = 'BA',
  Supercenter = 'Supercenter',
  WalmartExpress = 'Walmart Express',
  cadena = 'cadena',
}

export enum ImgCadena {
  BaPNG = 'ba.png',
  WePNG = 'we.png',
  WmPNG = 'wm.png',
}

//Campaña
// Generated by https://quicktype.io

export interface CampsResponse {
  tienda_id: string;
  tienda: Tienda;
  data: Datum[];
  camp: string;
}

export interface Datum {
  tienda_id: string;
  camp_nombre: string;
  concepto: string;
  info_id: number;
}

export interface Tienda {
  tienda_id: string;
  nombre: string;
  clave: string;
}
